adaptation_audio_package: 'C6B9B1A2-82CF-4124-BE78-18259716510A'
templates: |
  rooms = [kitchen|bedroom|living room|terrace|garage](room)
  room = [{in} {the} $rooms]
  list_of_rooms = [$room {{and} $room {{and} $room}}]
  devices = [lights|light|television|tv|radio|everything|all {the} devices|every device|all|all {the} lights|all {the} radios](device)
  device = [{the} {$rooms} $devices]
  list_of_devices = [$device {0.3: and $device {0.3: and $device}}]
  command = [turn|set|switch|put]
  command_on = [activate|enable|open|play]
  command_off = [deactivate|disable|close|shut]
  additions_beginning = [and|also]
  additions_end = [too|also]

  intent = [
    *turn_on {$command} $list_of_devices on {$list_of_rooms}
    *turn_on $command on $list_of_devices {$list_of_rooms}
    *turn_off {$command} $list_of_devices off {$list_of_rooms}
    *turn_off $command off $list_of_devices {$list_of_rooms}
    *turn_on {$command} $list_of_devices up {$list_of_rooms}
    *turn_on $command up $list_of_devices {$list_of_rooms}
    *turn_off {$command} $list_of_devices down {$list_of_rooms}
    *turn_off $command down $list_of_devices {$list_of_rooms}
    *turn_on {$command_on} $list_of_devices {$list_of_rooms}
    *turn_off {$command_off} $list_of_devices {$list_of_rooms}
  ]
  $intent {and $intent}

  *select {$additions_beginning} {[on|at|in|by]} {the} $rooms {$additions_end}
  *select {$additions_beginning} {the} $devices {$additions_end}
  *select {$additions_beginning} $devices {[on|at|in|by]} {the} $rooms {$additions_end}
  *select {$additions_beginning} {the} $rooms $devices {$additions_end}

  *turn_on $command {[it|them]} [on|up]
  *turn_off $command {[it|them]} [off|down]
  
  *turn_on $devices [on|up]
  *turn_off $devices [off|down]

  *turn_on [on|up]
  *turn_off [off|down]
