/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.speechly.decoder;

public class CResultWord {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CResultWord(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CResultWord obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public String getWord() {
    return SpeechlyDecoderInternalJNI.CResultWord_word_get(swigCPtr, this);
  }

  public long getStart_time() {
    return SpeechlyDecoderInternalJNI.CResultWord_start_time_get(swigCPtr, this);
  }

  public long getEnd_time() {
    return SpeechlyDecoderInternalJNI.CResultWord_end_time_get(swigCPtr, this);
  }

}
