/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.speechly.decoder;

public class DecoderHandle {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DecoderHandle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DecoderHandle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SpeechlyDecoderInternalJNI.delete_DecoderHandle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DecoderHandle() {
    this(SpeechlyDecoderInternalJNI.new_DecoderHandle(), true);
  }

}
