/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.speechly.decoder;

public interface SpeechlyDecoderInternalConstants {
  public final static int SPEECHLY_ERROR_MISMATCH_IN_MODEL_ARCHITECTURE = 8;
  public final static int SPEECHLY_ERROR_INVALID_MODEL = 16;
  public final static int SPEECHLY_ERROR_EXPIRED_MODEL = 32;
  public final static int SPEECHLY_ERROR_UNEXPECTED_PARAMETER = 64;
  public final static int SPEECHLY_ERROR_UNEXPECTED_PARAMETER_VALUE = 4;
  public final static int SPEECHLY_ERROR_MEMORY_ERROR = 2;
  public final static int SPEECHLY_ERROR_UNEXPECTED_ERROR = 1;
  public final static int SPEECHLY_ERROR_NONE = 0;
  public final static int SPEECHLY_DECODER_INFO_PROGRESS_MS_I = 500;
  public final static int SPEECHLY_VAD_CONFIG_SIGNAL_TO_NOISE_DB_F = 1000;
  public final static int SPEECHLY_VAD_CONFIG_NOISE_GATE_DB_F = 1001;
  public final static int SPEECHLY_VAD_CONFIG_NOISE_LEARN_HALFTIME_MS_I = 1002;
  public final static int SPEECHLY_VAD_CONFIG_SIGNAL_ACTIVATION_F = 1003;
  public final static int SPEECHLY_VAD_CONFIG_SIGNAL_RELEASE_F = 1004;
  public final static int SPEECHLY_VAD_CONFIG_SIGNAL_SUSTAIN_MS_I = 1005;
  public final static int SPEECHLY_VAD_CONFIG_SIGNAL_SEARCH_FRAMES_I = 1006;
  public final static int SPEECHLY_VAD_INFO_SIGNAL_DB_F = 1007;
  public final static int SPEECHLY_VAD_INFO_NOISE_LEVEL_DB_F = 1008;
  public final static int SPEECHLY_VAD_INFO_IS_SIGNAL_DETECTED_I = 1009;
}
