/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.speechly.decoder;

public class SpeechlyDecoderInternalJNI {
  public final static native long new_DecoderFactoryHandle();
  public final static native void delete_DecoderFactoryHandle(long jarg1);
  public final static native long new_DecoderHandle();
  public final static native void delete_DecoderHandle(long jarg1);
  public final static native String CResultWord_word_get(long jarg1, CResultWord jarg1_);
  public final static native long CResultWord_start_time_get(long jarg1, CResultWord jarg1_);
  public final static native long CResultWord_end_time_get(long jarg1, CResultWord jarg1_);
  public final static native long DecoderError_error_code_get(long jarg1, DecoderError jarg1_);
  public final static native long new_DecoderError();
  public final static native void delete_DecoderError(long jarg1);
  public final static native long DecoderFactory_CreateFromModelArchive(java.nio.ByteBuffer jarg1, long jarg2) throws com.speechly.decoder.DecoderException;
  public final static native long DecoderFactory_GetDecoder(long jarg1, DecoderFactoryHandle jarg1_, String jarg2) throws com.speechly.decoder.DecoderException;
  public final static native String DecoderFactory_GetAppId(long jarg1, DecoderFactoryHandle jarg1_) throws com.speechly.decoder.DecoderException;
  public final static native String DecoderFactory_GetBundleId(long jarg1, DecoderFactoryHandle jarg1_) throws com.speechly.decoder.DecoderException;
  public final static native void DecoderFactory_SetSegmentationDelay(long jarg1, DecoderFactoryHandle jarg1_, int jarg2) throws com.speechly.decoder.DecoderException;
  public final static native void DecoderFactory_SetBoostVocabulary(long jarg1, DecoderFactoryHandle jarg1_, String jarg2, float jarg3) throws com.speechly.decoder.DecoderException;
  public final static native void Decoder_WriteSamples(long jarg1, DecoderHandle jarg1_, float[] jarg2, long jarg3, int jarg4) throws com.speechly.decoder.DecoderException;
  public final static native long Decoder_WaitResults(long jarg1, DecoderHandle jarg1_) throws com.speechly.decoder.DecoderException;
  public final static native long Decoder_GetResults(long jarg1, DecoderHandle jarg1_) throws com.speechly.decoder.DecoderException;
  public final static native void Decoder_SetInputSampleRate(long jarg1, DecoderHandle jarg1_, int jarg2) throws com.speechly.decoder.DecoderException;
  public final static native void Decoder_EnableVAD(long jarg1, DecoderHandle jarg1_, int jarg2) throws com.speechly.decoder.DecoderException;
  public final static native int Decoder_GetParamI(long jarg1, DecoderHandle jarg1_, long jarg2) throws com.speechly.decoder.DecoderException;
  public final static native void Decoder_SetParamI(long jarg1, DecoderHandle jarg1_, long jarg2, int jarg3) throws com.speechly.decoder.DecoderException;
  public final static native float Decoder_GetParamF(long jarg1, DecoderHandle jarg1_, long jarg2) throws com.speechly.decoder.DecoderException;
  public final static native void Decoder_SetParamF(long jarg1, DecoderHandle jarg1_, long jarg2, float jarg3) throws com.speechly.decoder.DecoderException;
  public final static native int Decoder_GetNumSamples(long jarg1, DecoderHandle jarg1_);
  public final static native int Decoder_GetNumVoiceSamples(long jarg1, DecoderHandle jarg1_);
  public final static native int Decoder_GetNumCharacters(long jarg1, DecoderHandle jarg1_);
  public final static native String SpeechlyDecoderVersion();
  public final static native long SpeechlyDecoderBuild();
  public final static native void CResultWord_Destroy(long jarg1, CResultWord jarg1_);
  public final static native void DecoderFactory_Destroy(long jarg1, DecoderFactoryHandle jarg1_);
  public final static native void Decoder_Destroy(long jarg1, DecoderHandle jarg1_);
}
