declare module '@speechly/browser-ui/core/holdable-button'
declare module '@speechly/browser-ui/core/call-out'
declare module '@speechly/browser-ui/core/big-transcript'
declare module '@speechly/browser-ui/core/transcript-drawer'
declare module '@speechly/browser-ui/core/intro-popup'
