name: Rush build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
      - 'release/**'

env:
  WEBPACK_MODE: prd
  BROWSERSLIST_IGNORE_OLD_DATA: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 25
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: common/temp/pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.28.0
      - name: Setup Node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '16'
      - name: Check change log update
        run: node common/scripts/install-run-rush.js change --target-branch origin/main --verify
      - name: Install Dependencies
        run: node common/scripts/install-run-rush.js install --no-link
      - name: Link dependencies
        run: node common/scripts/install-run-rush.js link
      - name: Build Project
        run: node common/scripts/install-run-rush.js rebuild --verbose
      - name: Publish Components
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          node common/scripts/install-run-rush.js publish --apply --publish --target-branch main
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
