name: deploy fashion
on:
  push:
    branches:
      - main
    paths:
      - "demos/fashion-ecommerce/data/filter-config.csv"
      - "demos/fashion-ecommerce/voice-interface.yaml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          npm run preprocess
        working-directory: demos/fashion-ecommerce
      - name: Deploy
        if: ${{ success() }}
        uses: docker://speechly/cli:latest
        with:
          args: deploy -a ${{ secrets.APPID_FASHION }} demos/fashion-ecommerce/config -w
        env:
          SPEECHLY_APIKEY: ${{ secrets.SPEECHLY_APIKEY }}
