name: deploy analyzer
on:
  push:
    branches:
      - main
    paths:
      - "demos/analyzer/config/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://speechly/cli:latest
        with:
          args: deploy -a ${{ secrets.APPID_ANALYZER }} demos/analyzer/config -w
        env:
          SPEECHLY_APIKEY: ${{ secrets.SPEECHLY_APIKEY }}
