name: deploy smart-home-demo
on:
  push:
    branches:
      - main
    paths:
      - "demos/smart-home/config/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://speechly/cli:latest
        with:
          args: deploy -a ${{ secrets.APPID_SMART_HOME_DEMO }} demos/smart-home/config -w
        env:
          SPEECHLY_APIKEY: ${{ secrets.SPEECHLY_APIKEY }}
