name: deploy fashion
on:
  push:
    branches:
      - main
    paths:
      - "demos/fashion-ecommerce/config/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: docker://speechly/cli:latest
        with:
          args: deploy -a ${{ secrets.APPID_FASHION }} demos/fashion-ecommerce/config -w
        env:
          SPEECHLY_APIKEY: ${{ secrets.SPEECHLY_APIKEY }}
