name: deploy fast-food
on:
  push:
    branches:
      - main
    paths:
      - "demos/fast-food/config/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://speechly/cli:latest
        with:
          args: deploy -a ${{ secrets.APPID_FAST_FOOD_DEMO }} demos/fast-food/config -w
        env:
          SPEECHLY_APIKEY: ${{ secrets.SPEECHLY_APIKEY }}
