name: validate fast-food
on:
  pull_request:
    branches:
      - main
    paths:
      - "demos/fast-food/config/**"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://speechly/cli:latest
        with:
          args: validate -a ${{ secrets.APPID_FAST_FOOD_DEMO }} demos/fast-food/config
        env:
          SPEECHLY_APIKEY: ${{ secrets.SPEECHLY_APIKEY }}
